# site settings
baseURL = "https://guyueshui.github.io"
languageCode = "en"
defaultContentLanguage = "en" # en / zh-cn / ... (This field determines which i18n file to use)
title = "水阙"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"
footnoteReturnLinkContents = "↩"

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 9                                              # 首页每页显示的文章数
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

[author]                  # essential                     # 必需
  name = "Yychi"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# [permalinks]
#   post = "/:year/:month/:title/"

[[menu.main]]
  name = "Archives"
  weight = 2
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 3
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 4
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Sketch"
  weight = 5
  identifier = "sketch"
  url = "/sketch/"
[[menu.main]]
  name = "Tricks"
  weight = 6
  identifier = "tricks"
  url = "/tricks/"
[[menu.main]]
  name = "About"
  weight = 7
  identifier = "about"
  url = "/about/"

# [blackfriday]
#   # translate new line into linebreaks
#   # extensions = ["hardLineBreak"]
#   smartypants = false

[params]
  # Used to give a friendly message when you have an incompatible update
  version = "4.x" 
  debug = false # If true, load `eruda.min.js`. 
                # See https://github.com/liriliri/eruda
  since = "2018"  # Site creation time
  # site info (optional)
  logoTitle = "Yychi's log" # default: the title value
  keywords = ["水阙", "yychi"]
  description = "向往水的温柔，在心底打着卷儿。"
  # paginate of archives, tags and categories
  archivePaginate = 15
  # show 'xx Posts In Total' in archive page?
  showArchiveCount = true
  # The date format to use; for a list of valid formats, 
  # see https://gohugo.io/functions/format/
  dateFormatToUse = "January 2, 2006"
  # show word count and read time ?
  moreMeta = false
  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options
  # you can also close or open something in front matter for a single post, 
  # see more information from `archetypes/default.md`.
  toc = true                # 是否开启目录
  autoCollapseToc = false   # Auto expand and collapse toc
  fancybox = true           # 是否启用fancybox（图片可点击）
                            # see https://github.com/fancyapps/fancybox
  mathjax = false
  mathjaxEnableSingleDollar = true # 是否使用 $...$ 即可進行inline latex渲染
  mathjaxEnableAutoNumber = false  # 是否使用公式自动编号
  mathjaxUseLocalFiles = false     # You should install mathjax in `yout-site/static/lib/mathjax`
  postMetaInFooter = true   # contain author, lastMod, markdown link, license
  linkToMarkDown = true     # Only effective when hugo will output .md files
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key

  livereUID = ""            # LiveRe UID                  # 来必力

  baiduPush = false        # baidu push                  # 百度
  baiduAnalytics = ""      # Baidu Analytics
  baiduVerification = ""   # Baidu Verification
  googleVerification = ""  # Google Verification         # 谷歌

  # Link custom CSS and JS assets
  # (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  [params.publicCDN] # load these files from public cdn 启用公共CDN，需自行定义
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [params.outdatedInfoWarning]
    enable = false
    hint = 30   # 如果文章最后更新于这天数之前，显示提醒
    warn = 180  # 如果文章最后更新于这天数之前，显示警告

  [params.gitment]
    # Gitment is a comment system based on GitHub issues.
    # see https://github.com/imsun/gitment
    owner = "guyueshui"   # Your GitHub ID
    repo = "gitment"      # The repo to store comments
    clientId = "e8af7d1d7737c71052fa"                           # Your client ID
    clientSecret = "17b8e50e7b9d4bbd2177b30902b4bc80b3245f3f"   # Your client secret

  [params.gitalk]
    # Gitalk is a comment system based on GitHub issues.
    # see https://github.com/gitalk/gitalk
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.flowchartDiagrams] 
    # see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
    enable = false
    options = ""

  [params.sequenceDiagrams]
    # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
    enable = false
    options = ""            # default: "{theme: 'simple'}"

  [params.busuanzi]         # count web traffic by busuanzi
    enable = true
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]           # 文章打赏
    enable = true
    wechat = "https://s2.ax1x.com/2019/01/18/k9S5a6.png" # 微信二维码
    alipay = "https://s2.ax1x.com/2019/01/18/k9SvZt.jpg" # 支付宝二维码

  [params.social]           # 社交链接
    a-email = "mailto:guyueshui002@gmail.com"
    #b-stack-overflow = "http://localhost:1313"
    #c-twitter = "http://localhost:1313"
    #d-facebook = "http://localhost:1313"
    #e-linkedin = "http://localhost:1313"
    #f-google = "http://localhost:1313"
    g-github = "https://github.com/guyueshui"
    #h-weibo = "http://localhost:1313"
    #i-zhihu = "http://localhost:1313"
    #j-douban = "http://localhost:1313"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "http://localhost:1313"
    #n-gitlab = "http://localhost:1313"
    #o-bilibili = "http://localhost:1313"

[privacy]
  # See https://gohugo.io/about/hugo-and-gdpr/
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
# [mediaTypes]
#   [mediaTypes."text/plain"]
#     suffixes = ["md"]
# 
# [outputFormats.MarkDown]
#   mediaType = "text/plain"
#   isPlainText = true
#   isHTML = false
# 
# [outputs]
#   home = ["HTML", "RSS"]
#   page = ["HTML", "MarkDown"]
#   section = ["HTML", "RSS"]
#   taxonomy = ["HTML", "RSS"]
#   taxonomyTerm = ["HTML"]

# Add reveal.js support for web presentation.
# see https://github.com/dzello/reveal-hugo#recipes
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "moon"

#####################
#  Markup settings  #
#####################
# see https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # set to true for rendering raw html.
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
