baseURL = "https://example.com"
languageCode = "en-us"
title = "水阙"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
#enableGitInfo = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "札记"
    url = "/sketch/"
    weight = 5

  [[menu.main]]
    name = "Tricks"
    url = "/tricks/"
    weight = 6

  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 7

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2018
    author = "Yychi"	# Author's name
    avatar = "/img/me/avatar.png"	# Author's avatar
	favicon = "/cali.png"
    subtitle = "向往水的温柔，在心底打着卷儿。"	# Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "posts" # post or other

    google_verification = ""
   
    description = "PLOG" # site description
    keywords = "水阙" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "guyueshui"
    Twitter = "fyuyychi"
    Email   = "guyueshui002@gmail.com"
    #Instagram = "xxoo"
    #Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    #Facebook = "xxoo"
    #Telegram = "xxoo"
    #Dribbble = "xxoo"
    #Medium = "xxoo"
