name: Blog deploy

on:
  push:
    branches:
      - src

env:
  TZ: Asia/Shanghai

jobs:
  blog-deploy:
    name: Hugo blog build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Build
        run: hugo --config even-config.toml

      - name: Deploy to master
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
